project_id = "fxfkklvbjrrxzzgnoiam"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.calendly-booking]
verify_jwt = false